### ISSUE TITLE
Broken TikZ SVGs on macOS

### ISSUE THREAD

**Issue by davidstraka2** [davidstraka2/wootom#44]
The SVG images in the preview of the `!tikz` outer environments are broken on macOS. Only the text is shown, all of it aligned to the top of the image, no other shapes are displayed. See an image example below.

![tikz-svg-error](https://user-images.githubusercontent.com/32021723/125231512-303dbe00-e2db-11eb-9bbe-8b98ab2d2192.png)

Compare that to the correctly displayed SVG on Windows 10 and Arch Linux, shown below.

![tikz-svg-correct](https://user-images.githubusercontent.com/32021723/125231780-b0642380-e2db-11eb-8e4e-2f6aacd0bd53.png)

The WooWoo source of the `.Figure` object from the examples shown is included below. Note that the preview examples use dark editor theme and inverted SVG colors.

```
.Figure:
  label: fig-vektory

  !tikz:
    filename: fig-vektory-1

    \draw[blue,thick,->] (0,0) -- (3,3) node[anchor=south east] {$\alpha \cdot \vec a,\, \alpha > 1$};
    \draw[very thick,black,->] (0,0) -- (2,2) node[anchor=north west] {$\vec a$};
    \draw[red,very thick,->] (0,0) -- (1,1) node[anchor=south east] {$\alpha \cdot \vec a,\, 0 < \alpha < 1$};
    \draw[brown,thick,->] (0,0) -- (-1,-1) node[anchor=north west] {$\alpha \cdot \vec a,\, \alpha < 0$};
    \fill[black] (0,0) circle (2pt) node[anchor=south east] {$O$};
    \node at (1,-2) {(a)};

  !tikz:
    filename: fog-vektory-2
    options: 'scale=1.5'

    \draw[black,thick,->] (0,0) -- (.5,2) node[above] {$\vec a$};
    \draw[blue,thick,->] (0,0) -- (1.5,-.5) node[below] {$\vec b$};
    \draw[blue,dashed] (.5,2) -- (2,1.5);
    \draw[black,dashed] (1.5,-.5) -- (2,1.5);
    \draw[red,very thick,->] (0,0) -- (2,1.5) node[anchor=south west] {$\vec a + \vec b$};
    \node at (1,-1.5) {(b)};
    \fill[black] (0,0) circle (1pt) node[left] {$O$};

  .caption:

    Geometrický význam násobení vektoru číslem (a) a sčítání vektorů (b).
```

The TeX file used for generating the SVG, the DVI file generated from it on macOS using `latex` (from an up to date MacTeX distribution), the log file from the process, as well as both the broken SVG generated on macOS and correct SVG generated on Windows 10 - both using `dvisvgm` included in the TeX distribution (that being full texlive on Windows) - can all be found attached in [this zip archive attachment](https://github.com/davidstraka2/wootom/files/6798669/fig-vektory-1.zip).

**Comment by davidstraka2** [comment]
The problem has been isolated to be with dvisvgm on macOS. A minimal reproducible example has been created and checked utilizing GitHub Actions. [An issue](https://github.com/mgieseki/dvisvgm/issues/157) has been submitted to the dvisvgm issue tracker.

TeX source of a minimal reproducible example:

```tex
\documentclass[tikz]{standalone}
\begin{document}
  \begin{tikzpicture}[]
    \draw (0,0) -- (1,1) node[pos=0.5]{x};
  \end{tikzpicture}
\end{document}
```

A GitHub Actions workflow to generate outputs on macOS and upload job artifacts:

```yml
name: CI
on: [push, pull_request]
jobs:
  Test:
    name: Test macOS
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install MacTex
        run: |
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew install --cask mactex
          echo "/Library/TeX/texbin" >> $GITHUB_PATH
      - name: Process image
        run: |
          latex image.tex
          dvisvgm --no-fonts image.dvi
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            image.dvi
            image.log
            image.svg
```
